### ISSUE TITLE
junit5-allure fixes

### ISSUE THREAD

**Issue by sskorol** [bonigarcia/mastering-junit5#1]
Currently `allure-gradle` doesn't support junit5 (see https://github.com/allure-framework/allure-gradle/issues/17). However, `junit5-allure` module still requires some configuration tweaks. Will create a PR for that.

**Comment by bonigarcia** [comment]
Cool, thank you!

**Comment by bonigarcia** [comment]
Thanks to PR #2 now the allure report is stored where expected, but unfortunately the command `gradlew allureReport` seems not be working yet. In Linux I get this:

```
$ ./gradlew allureReport

> Configure project :
Gradle now uses separate output directories for each JVM language, but this build assumes a single directory for all classes from a source set. This behaviour has been deprecated and is scheduled to be removed in Gradle 5.0


FAILURE: Build failed with an exception.

* What went wrong:
Task 'allureReport' not found in root project 'junit5-allure'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

**Comment by sskorol** [comment]
@bonigarcia `allureReport` is `allure-plugin` task. As plugin doesn't support junit5 yet, I've temporary removed it from build.gradle.

See #2 description. There's a link on `allure-commandline` installation. You can install it via `brew`, `scoop` or whatever, and then use `allure` script directly instead of plugin.

That's why I've mentioned `allure serve build/allure-results` command in PR.

**Comment by bonigarcia** [comment]
Understood. Thank you very much for your help!
