### ISSUE TITLE
Paralellel execution doesn't work properly

### ISSUE THREAD

**Issue by ness-nikolajsokunevs** [bonigarcia/mastering-junit5#1117]
Module: junit5-cucumber-selenium
Chrome: 117
macOs Ventura 13.4

**Step to reproduce:**
1. Update junit-platform.properties
`cucumber.publish.quiet=true
cucumber.execution.parallel.enabled=true
cucumber.execution.parallel.config.strategy=fixed
cucumber.execution.parallel.config.fixed.parallelism=2`

3. Duplicate test scenarios(login.feature) to increase the total number of tests. For example create 10 tests.

2. Run the 'CucumberTest' java class

**Expected:**
Tests should be executed in parallel in 2 thread

**Actual:**
All tests started simultaneously in 10 Threads(thread number=total number of tests)

**Comment by bonigarcia** [comment]
No clue, sorry.
