### ISSUE TITLE
Please any help would be great

### ISSUE THREAD

**Issue by dpeedah** [bonigarcia/mastering-junit5#237]
Been trying to resolve issues of using junit 5 with cucumber, when i run mvn test , cucumber does not appear to be actively doing anything, however, when i click on my runner and run it, cucumber sees the feature file, but says no tests where found. It's really critical.

Link to my slack post:https://stackoverflow.com/questions/67847818/maven-junit-5-cucumber-not-running-tests

**Comment by bonigarcia** [comment]
No clue, sorry.
