### ISSUE TITLE
Where is cucumber-jupiter artifact ?

### ISSUE THREAD

**Issue by devbhuwan** [bonigarcia/mastering-junit5#3]
Dear @bonigarcia from where you have use `info.cukes:cucumber-jupiter:1.2.6-SNAPSHOT` artifact.

Actually, I unable find this release artifact in the repositories.

**Comment by bonigarcia** [comment]
Sorry for the late reply @devbhuwan.

I built this artifact from the following [PR](https://github.com/cucumber/cucumber-jvm/pull/1258) in cucumber-jvm. Unfortunately, according last comments of the Cucumber maintainers, the extension approach is not going to be merged in the master branch. It seems they plan to implement a JUnit 5 test engine instead.

Therefore, I am going to remove  the `CucumberExtension` from my example, and I will keep on eye on the evolution of Cucumber to update the example when the official support is available.
