### ISSUE TITLE
junit5-cucumber is broken

### ISSUE THREAD

**Issue by jsalido** [bonigarcia/mastering-junit5#6]
I did see issue https://github.com/bonigarcia/mastering-junit5/issues/3, but the fact remains that as is, the junit5-cucumber example is still broken and fails. Removing the CucumberExtension dependency did not fix nor made the problem go away.

➜  junit5-cucumber git:(master) mvn test
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building junit5-cucumber 1.0.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ junit5-cucumber ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ junit5-cucumber ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ junit5-cucumber ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/jsalido/code/mastering-junit5/junit5-cucumber/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ junit5-cucumber ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ junit5-cucumber ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running io.github.bonigarcia.CucumberTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.058 sec <<< FAILURE! - in io.github.bonigarcia.CucumberTest
runTests(Stream)  Time elapsed: 0.055 sec  <<< FAILURE!
org.junit.jupiter.api.extension.ParameterResolutionException: No ParameterResolver registered for parameter [java.util.stream.Stream<org.junit.jupiter.api.DynamicTest> arg0] in executable [public java.util.stream.Stream<org.junit.jupiter.api.DynamicTest> io.github.bonigarcia.CucumberTest.runTests(java.util.stream.Stream<org.junit.jupiter.api.DynamicTest>)].

Results :

Failed tests:
  CucumberTest.runTests » ParameterResolution No ParameterResolver registered fo...

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.433 s
[INFO] Finished at: 2018-02-08T21:51:21Z
[INFO] Final Memory: 31M/2944M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project junit5-cucumber: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/jsalido/code/mastering-junit5/junit5-cucumber/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by bonigarcia** [comment]
Unfortunately there is no official support for Cucumber in JUnit 5 yet (the extension approach was not finally merged in the master branch). You can find more info [here](https://github.com/cucumber/cucumber-jvm/issues/1149) .

I have just removed the logic of this test to avoid a failure when running the tests in the `junit5-cucumber` project. I keep an eye on the Cucumber developments, and as far it is available, I will incorporate as an example in this example project.
