### ISSUE TITLE
Cucumber generating empty reports

### ISSUE THREAD

**Issue by vainamonen** [bonigarcia/mastering-junit5#609]
Hi,
If I add some properties:
cucumber.publish.enabled=false
cucumber.plugin=pretty, summary, html:target/cucumber-reports/cucumber.html, json:target/cucumber-reports/cucumber.json, junit:target/cucumber-reports/cucumber.xml

to junit-platform.properties in module junit5-cucumber then the directory cucumber-reports in target is created.
It has 3 files, but each one is empty.

Do you know how to fix it?

**Comment by bonigarcia** [comment]
I don't know, sorry.
