### ISSUE TITLE
Please provide setup details to run these examples

### ISSUE THREAD

**Issue by ajmersaini** [bonigarcia/mastering-junit5#7]

**Comment by bonigarcia** [comment]
See [Mastering Software Testing with JUnit 5](https://www.amazon.com/gp/product/1787285731/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=1787285731&linkCode=as2&tag=boni0a-20&linkId=a0b9a99160003dfd49a797906e8c191b).
